# -*- coding: utf-8 -*-
"""dashboard_4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mERHOpMZDMdmBToUFLwXVtDG3oZvLHV0
"""

import streamlit as st
import sqlite3
import pandas as pd
from streamlit_autorefresh import st_autorefresh

DB_FILE = "telemetry.db"

st.set_page_config(page_title="Telemetry Dashboard", layout="wide")

# Auto-refresh every 5 seconds
st_autorefresh(interval=5000, key="telemetryrefresh")

st.title("Telemetry Dashboard")


def load_data():
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql("SELECT * FROM telemetry", conn)
    conn.close()
    return df


def load_processes():
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql("SELECT * FROM processes ORDER BY id DESC LIMIT 20", conn)
    conn.close()
    return df


def calculate_confidence(df):
    if len(df) < 5:
        return 0

    recent = df.tail(5)
    cpu_avg = recent["cpu"].mean()

    if cpu_avg > 80:
        return 90
    elif cpu_avg > 60:
        return 70
    elif cpu_avg > 40:
        return 50
    else:
        return 20


df = load_data()
proc_df = load_processes()

if df.empty:
    st.warning("No data found. Run collector first.")
else:
    latest = df.iloc[-1]
    confidence = calculate_confidence(df)

    st.subheader("Latest Metrics")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("CPU", f"{latest['cpu']}%")
    col2.metric("Memory", f"{latest['memory']}%")
    col3.metric("Disk", f"{latest['disk']}%")
    col4.metric("Battery", f"{latest['battery']}%")

    st.subheader("AI Diagnosis")

    messages = []
    root_cause = None

    if latest["cpu"] > 80:
        messages.append("High CPU usage detected")
        if not proc_df.empty:
            top = proc_df.iloc[0]
            root_cause = top["name"]

    if latest["memory"] > 80:
        messages.append("High memory usage detected")

    if latest["disk"] > 90:
        messages.append("Disk almost full")

    if not messages:
        messages.append("System is running normally")

    for m in messages:
        st.write("•", m)

    st.subheader("Confidence Score")
    st.metric("Confidence", f"{confidence}%")

    st.subheader("Explanation")
    if root_cause:
        st.write(f"Likely caused by: {root_cause}")
    else:
        st.write("No single dominant process detected")

    st.subheader("Top Processes")
    if not proc_df.empty:
        st.dataframe(proc_df[["name", "cpu", "memory"]], use_container_width=True)

    st.subheader("Trends")
    st.line_chart(df[["cpu", "memory", "disk"]])