# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oBJuRa1umXe3HArmd-vuyPoQbhv1-eZ
"""

import streamlit as st
import sqlite3
import pandas as pd

DB_FILE = "telemetry.db"

st.title("Telemetry Dashboard")

def load_data():
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql("SELECT * FROM telemetry", conn)
    conn.close()
    return df

df = load_data()

if df.empty:
    st.warning("No data found. Run collector first.")
else:
    st.subheader("Latest Metrics")

    latest = df.iloc[-1]

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("CPU", f"{latest['cpu']}%")
    col2.metric("Memory", f"{latest['memory']}%")
    col3.metric("Disk", f"{latest['disk']}%")
    col4.metric("Battery", f"{latest['battery']}%")

    st.subheader("Trends")
    st.line_chart(df[["cpu", "memory", "disk"]])