# -*- coding: utf-8 -*-
"""dashboard_3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STwaFT8tw_GDImhk9FDFHwyW8vFUZNG6
"""

import streamlit as st
import sqlite3
import pandas as pd

DB_FILE = "telemetry.db"

st.title("Telemetry Dashboard")


def load_data():
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql("SELECT * FROM telemetry", conn)
    conn.close()
    return df


def load_processes():
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql("SELECT * FROM processes ORDER BY id DESC LIMIT 20", conn)
    conn.close()
    return df


df = load_data()
proc_df = load_processes()

if df.empty:
    st.warning("No data found. Run collector first.")
else:
    st.subheader("Latest Metrics")

    latest = df.iloc[-1]

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("CPU", f"{latest['cpu']}%")
    col2.metric("Memory", f"{latest['memory']}%")
    col3.metric("Disk", f"{latest['disk']}%")
    col4.metric("Battery", f"{latest['battery']}%")

    st.subheader("Diagnosis")

    messages = []

    if latest["cpu"] > 80:
        messages.append("High CPU usage detected")

    if latest["memory"] > 80:
        messages.append("High memory usage detected")

    if latest["disk"] > 90:
        messages.append("Disk almost full")

    if latest["battery"] is not None and latest["battery"] < 20:
        messages.append("Battery is low")

    if not messages:
        messages.append("System is running normally")

    for m in messages:
        st.write("•", m)

    st.subheader("Top Processes")

    if not proc_df.empty:
        st.dataframe(proc_df[["name", "cpu", "memory"]])

    st.subheader("Trends")
    st.line_chart(df[["cpu", "memory", "disk"]])