# -*- coding: utf-8 -*-
"""Collector_3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcVChDZC3isGZY4wnI574cITfYSA7LcG
"""

import time
import sqlite3
import psutil
from datetime import datetime

DB_FILE = "telemetry.db"


def init_db():
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS telemetry (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            cpu REAL,
            memory REAL,
            disk REAL,
            battery REAL
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS processes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            name TEXT,
            pid INTEGER,
            cpu REAL,
            memory REAL
        )
    """)

    conn.commit()
    conn.close()


def get_metrics():
    battery = psutil.sensors_battery()

    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "cpu": psutil.cpu_percent(interval=1),
        "memory": psutil.virtual_memory().percent,
        "disk": psutil.disk_usage("C:\\").percent,
        "battery": battery.percent if battery else None
    }


def get_top_processes():
    processes = []

    for p in psutil.process_iter(['pid', 'name', 'memory_percent']):
        try:
            cpu = p.cpu_percent()
            processes.append({
                "pid": p.info['pid'],
                "name": p.info['name'],
                "cpu": cpu,
                "memory": p.info['memory_percent']
            })
        except:
            continue

    return sorted(processes, key=lambda x: x["cpu"], reverse=True)[:5]


def save_data(data, processes):
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()

    cur.execute("""
        INSERT INTO telemetry (timestamp, cpu, memory, disk, battery)
        VALUES (?, ?, ?, ?, ?)
    """, (
        data["timestamp"],
        data["cpu"],
        data["memory"],
        data["disk"],
        data["battery"]
    ))

    for p in processes:
        cur.execute("""
            INSERT INTO processes (timestamp, name, pid, cpu, memory)
            VALUES (?, ?, ?, ?, ?)
        """, (
            data["timestamp"],
            p["name"],
            p["pid"],
            p["cpu"],
            p["memory"]
        ))

    conn.commit()
    conn.close()


def run():
    init_db()
    print("Collector with processes started...\n")

    while True:
        data = get_metrics()
        processes = get_top_processes()

        save_data(data, processes)

        print(data)

        time.sleep(3)


if __name__ == "__main__":
    run()