# -*- coding: utf-8 -*-
"""Collector.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXwEv62dyAfo9Er_mMsTmbdKS8HE1Ite
"""

import time
import psutil
from datetime import datetime

print("Starting simple telemetry collector...\n")

while True:
    cpu = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory().percent
    disk = psutil.disk_usage("C:\\").percent

    battery = psutil.sensors_battery()
    battery_percent = battery.percent if battery else None

    print(f"{datetime.now()}")
    print(f"CPU: {cpu}%")
    print(f"Memory: {memory}%")
    print(f"Disk: {disk}%")
    print(f"Battery: {battery_percent}%")
    print("-" * 40)

    time.sleep(3)