# -*- coding: utf-8 -*-
"""Collector_2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1um8aXzK0CwjJuDEJ8HENnR-D53J2WYMQ
"""

import time
import sqlite3
import psutil
from datetime import datetime

DB_FILE = "telemetry.db"

def init_db():
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS telemetry (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT,
            cpu REAL,
            memory REAL,
            disk REAL,
            battery REAL
        )
    """)

    conn.commit()
    conn.close()

def save_data(data):
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()

    cur.execute("""
        INSERT INTO telemetry (timestamp, cpu, memory, disk, battery)
        VALUES (?, ?, ?, ?, ?)
    """, (
        data["timestamp"],
        data["cpu"],
        data["memory"],
        data["disk"],
        data["battery"]
    ))

    conn.commit()
    conn.close()

def get_metrics():
    battery = psutil.sensors_battery()

    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "cpu": psutil.cpu_percent(interval=1),
        "memory": psutil.virtual_memory().percent,
        "disk": psutil.disk_usage("C:\\").percent,
        "battery": battery.percent if battery else None
    }

def run():
    init_db()
    print("Collector with DB started...\n")

    while True:
        data = get_metrics()
        save_data(data)

        print(data)

        time.sleep(3)

if __name__ == "__main__":
    run()